import { call } from "./invoke";
import type { ClientSettings, ConnectionInfo } from "../types/client";
import type { ClientSettingsFileState, DirectoryEntryInfo, WindowLayoutState } from "../types/files";

export const desktopApi = {
  getConnections: () => call<ConnectionInfo[]>("get_connections"),
  executeScript: (id: string, script: string) => call<boolean>("execute_script", { id, script }),
  setSourceMapInstance: (id: string) => call<boolean>("set_sourcemap_instance", { id }),
  getLatestSourceMap: (id?: string | null) => call("get_latest_sourcemap", { id: id ?? null }),
  listSystemFonts: () => call<string[]>("list_system_fonts"),
  openFileDialog: () => call<string>("open_file_dialog"),
  saveFileDialog: () => call<string>("save_file_dialog"),
  openThemeFileDialog: () => call<string>("open_theme_file_dialog"),
  saveThemeFileDialog: (defaultFileName: string) => call<string>("save_theme_file_dialog", { defaultFileName }),
  openClientSettingsFileDialog: () => call<string>("open_client_settings_file_dialog"),
  saveClientSettingsFileDialog: (defaultFileName: string) => call<string>("save_client_settings_file_dialog", { defaultFileName }),
  openThemeMediaFileDialog: () => call<string>("open_theme_media_file_dialog"),
  openFolderInExplorer: (path: string) => call<boolean>("open_folder_in_explorer", { path }),
  ensureIgnoreFolder: (basePath: string) => call<boolean>("ensure_ignore_folder", { basePath }),
  createDirectory: (path: string) => call<boolean>("create_directory", { path }),
  directoryExists: (path: string) => call<boolean>("directory_exists", { path }),
  renameFile: (oldPath: string, newPath: string) => call<boolean>("rename_file", { oldPath, newPath }),
  fileExists: (path: string) => call<boolean | null>("file_exists", { path }),
  renameDirectory: (oldPath: string, newPath: string) => call<boolean>("rename_directory", { oldPath, newPath }),
  deleteFile: (path: string) => call<boolean>("delete_file", { path }),
  deleteDirectory: (path: string) => call<boolean>("delete_directory", { path }),
  readFile: (path: string) => call<string>("read_file", { path }),
  readFileBase64: (path: string) => call<string>("read_file_base64", { path }),
  writeFile: (path: string, content: string) => call<boolean>("write_file", { path, content }),
  getScriptsDirectory: () => call<string>("get_scripts_directory_cmd"),
  getAutoexecDirectory: () => call<string>("get_autoexec_directory_cmd"),
  getWorkspaceDirectory: () => call<string>("get_workspace_directory_cmd"),
  listFilesInDirectory: (path: string) => call<string[]>("list_files_in_directory", { path }),
  listDirectoryEntries: (path: string) => call<DirectoryEntryInfo[]>("list_directory_entries", { path }),
  saveFileToScripts: (filename: string, content: string) => call<string>("save_file_to_scripts", { filename, content }),
  writeLayoutTempFile: (content: string, existingPath?: string | null) => call<string>("write_layout_temp_file", { content, existingPath }),
  readLayoutTempFile: (path: string) => call<string | null>("read_layout_temp_file", { path }),
  deleteLayoutTempFile: (path: string) => call<boolean>("delete_layout_temp_file", { path }),
  getWindowLayoutState: () => call<WindowLayoutState | null>("get_window_layout_state"),
  restoreWindowLayoutState: (state: WindowLayoutState) => call<boolean>("restore_window_layout_state", { state }),
  getClientSettingsFileState: () => call<ClientSettingsFileState>("get_client_settings_file_state"),
  updateClientSettings: (client: ClientSettings) => call("update_client_settings", client as unknown as Record<string, unknown>),
  setWebviewSuspended: (labels: string[], suspended: boolean) => call("set_webview_suspended", { labels, suspended }),
  setTopmost: (topmost: boolean) => call("set_topmost", { topmost }),
};
